/*

	FILE SYSTEM OF NINPONIX DATABASE SYSTEM IO (MADE BY CHAMUTH CHAMANDANA) 

	NINPONIX DATABASE SYSTEM IS BASED ON TABLES JUST LIKE MOST OF THE DATABASE PROGRAMMING LANGUAGES AND STRUCTURES.

	1. [DECLARATION]
	2. [ELEMENTS]

	-----------------------------------------------------------------------
	[KEY][COLUMN1][COLUMN2][COLUMN3][COLUMN4]
	[ROW1-KEY][ROW1-COLUMN1][ROW1-COLUMN2][ROW1-COLUMN3][ROW1-COLUMN4]
	[ROW2-KEY][ROW2-COLUMN1][ROW2-COLUMN2][ROW2-COLUMN3][ROW2-COLUMN4]
	
	EXAMPLE -----------------------------------------------------------------------

	index(int);stdname(string);stdclass(string);stdtelephone(int);stdaddress(string);
	20112;Chamuth Chamandana;10-A;756281355;Ratakoopiwatta, Hiriwadunna, Kegalle;

	------DEFINITIONS-------
	KEY = A.K.A. PRIMARY KEY ON MANY PLATFORMS. THIS IS THE PIECE OF DATA THAT IS USED TO DISTINGUISH A CERTAIN DATA FROM OTHERS

	THIS SOFTWARE (OPEN-SOURCE) IS PROTECTED BY NINPONIX CORPORATION, AND IT'S SUBSIDAIRIES FOR THE DEVELOPMENT OF INTERNAL SOFTWARE,
	AN ACCEPTABLE LICENSE FROM AN AUTHORIZED PERSONNEL MUST BE GRANTED BEFORE USING NINPONIX DATABASE SYSTEMS ON YOUR APPLICATIONS.
	- CHAMUTH CHAMANDANA, CEO OF NINPONIX CORPORATION.

*/